const asset = (path: string) => `${import.meta.env.BASE_URL}assets/${path}`;

export const ASSETS = {
  logo: asset("logo/mundo-polar-logo.png"),
  shared: {
    footerMarks: asset("shared/footer-marks.png"),
  },
  home: {
    hero: asset("home/hero-familia-invierno.png"),
    familyAndPet: asset("home/familia-y-mascota.png"),
    categoryWomen: asset("home/categoria-mujer.png"),
    categoryMen: asset("home/categoria-hombre.png"),
    categoryKids: asset("home/categoria-ninos.png"),
    categoryPets: asset("home/categoria-mascotas.png"),
    winterCollectionBanner: asset("home/banner-coleccion-invierno.png"),
  },
  nosotros: {
    hero: asset("nosotros/hero-historia.png"),
    story01: asset("nosotros/historia-01.png"),
    story02: asset("nosotros/historia-02.png"),
    story03: asset("nosotros/historia-03.png"),
    story04: asset("nosotros/historia-04.png"),
    story05: asset("nosotros/historia-05.png"),
    story06: asset("nosotros/historia-06.png"),
  },
  ofertas: {
    hero: asset("ofertas/hero-ofertas-invierno.png"),
    categoryBackground: asset("ofertas/fondo-categorias.png"),
    categoryJackets: asset("ofertas/categoria-casacas.png"),
    categoryThermalSets: asset("ofertas/categoria-conjuntos-termicos.png"),
    categoryScarves: asset("ofertas/categoria-bufandas.png"),
    categoryGloves: asset("ofertas/categoria-guantes.png"),
    categoryBoots: asset("ofertas/categoria-botas.png"),
    kidsCollectionBanner: asset("ofertas/banner-coleccion-infantil.png"),
    trendsBanner: asset("ofertas/banner-tendencias.png"),
    testimonial01: asset("ofertas/testimonio-01.png"),
    testimonial02: asset("ofertas/testimonio-02.png"),
    testimonial03: asset("ofertas/testimonio-03.png"),
  },
  products: {
    hoodedBrownJacket: asset("products/chaqueta-capucha-marron.png"),
    shortBrownCoat: asset("products/abrigo-corto-marron.png"),
    beigeSweater: asset("products/sweater-poliester-beige.png"),
    gildanHeavyCottonShirt: asset("products/camiseta-gildan-heavy-cotton.png"),
    turtleneckSweater: asset("products/sweater-cuello-alto.png"),
    waterproofJacket: asset("products/casaca-impermeable.png"),
    turtleneckBaseLayer: asset("products/turtleneck-base-layer.png"),
    turtleneckSlimFit: asset("products/turtleneck-slim-fit.png"),
    knitDress: asset("products/vestido-tejido.png"),
    stripedBrownTop: asset("products/top-rayas-marron.png"),
    woolSocks: asset("products/medias-lana.png"),
    winterBoots: asset("products/botas-invierno.png"),
    mensBluePolo: asset("products/polo-azul-hombre.png"),
    woolBeanie: asset("products/gorro-lana.png"),
    winterHeadband: asset("products/vincha-invierno.png"),
    knitTop: asset("products/top-tejido.png"),
    winterSweater: asset("products/sweater-invierno.png"),
    linenDress: asset("products/vestido-lino.png"),
    whitePolo: asset("products/polo-blanco.png"),
    polarSet: asset("products/conjunto-polar.png"),
    ribbedTurtleneck: asset("products/turtleneck-acanalado.png"),
  },
} as const;
